# -*- coding: utf-8 -*-
"""Approach4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NkIK-YFUr8t-2WGGjPTCgMBDJBLBSrn3
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn import metrics as met
from sklearn import neighbors as nei
from sklearn import decomposition as dec
from sklearn import manifold as man

df = pd.read_csv("train.csv")

df.head()

df.isnull().sum()

train = df.pivot(index="userID", columns="movieID", values="rating")
train.head()

train.shape

test = pd.read_csv("test_without_labels.csv")
test.head()

train_scaled = train - train.mean(axis=1).values.reshape(-1, 1)
train_scaled.fillna(0, inplace=True)
train_scaled.head()

testn = pd.DataFrame()
testn["userID"] = test["IDs"].str.split("_").apply(lambda x:x[0])
testn["movieID"] = test["IDs"].str.split("_").apply(lambda x:x[1])
testn.head()

testn.shape

svd = dec.TruncatedSVD(n_components=100, algorithm="randomized")
train_svd = svd.fit_transform(train_scaled)
train_svd.shape

train_svd # users to concepts
movies = svd.components_.T # movies to concepts
movies.shape

test_user = train_scaled.loc[movie:movie, :]
test_user_svd = svd.transform(test_user)
test_user

test_user_svd.shape

idx = list(train_scaled.columns).index(2683)
idx

a = train_scaled.columns
a[2480]

testn.head()

test_user_svd.dot(myMovie_vec.reshape(100, -1))[0][0]

preds = []
testusers = testn["userID"].values
#len(testusers)
for i in range(len(testusers)):
  #print(testusers[i])
  userId = int(testusers[i])
  movie = int(testn.iloc[i,1])
  #print(movie)
  k = 22
  test_user = train_scaled.loc[userId:userId, :]
  test_user_svd = svd.transform(test_user)

  idx = list(train_scaled.columns).index(movie)
  myMovie_vec = movies[idx]

  std = test_user_svd.dot(myMovie_vec.reshape(100, -1))[0][0]
  avg = train.loc[userId,:].mean()
  pred = avg + std
  preds.append(pred)
'''
  filtered_indices = train[np.isnan(train.loc[:, userId]) == False].index
  filtered_train = train_scaled.loc[filtered_indices, :]

  if len(filtered_train) > 0:
    if len(filtered_train) < k:
      k = len(filtered_train)

    nn = nei.NearestNeighbors(n_neighbors=k, metric="cosine", algorithm="brute")
    nn.fit(filtered_train)
    close_indices = nn.kneighbors(test_user, return_distance=False)[0]
    std = filtered_train.iloc[close_indices, :][userId].mean()
'''

testnew = pd.concat([test,pd.Series(preds)],axis=1)
testnew = testnew.rename(columns={0:"rating"})
testnew.head()

testnew.to_csv("svd.csv", index=False)